name: component_library
description: A new Flutter package for providing various themes for the proejcts.
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  adaptive_breakpoints: ^0.1.4
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  google_fonts: ^3.0.1


dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1

flutter: